#pragma once

// carb
#include "carb/BindingsUtils.h"
#include "carb/CarbWindows.h"
#include "carb/ClientUtils.h"
#include "carb/Defines.h"
#include "carb/Error.h"
#include "carb/FindPlugins.h"
#include "carb/Format.h"
#include "carb/Framework.h"
#include "carb/FrameworkUtils.h"
#include "carb/IObject.h"
#include "carb/Interface.h"
#include "carb/InterfaceUtils.h"
#include "carb/Memory.h"
#include "carb/ObjectUtils.h"
#include "carb/PluginCoreUtils.h"
#include "carb/PluginInitializers.h"
#include "carb/PluginUtils.h"
#include "carb/RString.h"
#include "carb/RenderingTypes.h"
#include "carb/SdkVersion.h"
#include "carb/StartupUtils.h"
#include "carb/Strong.h"
#include "carb/Types.h"
#include "carb/Version.h"
// #include "carb/assert/AssertUtils.h"
// #include "carb/assert/IAssert.h"
// #include "carb/assets/AssetsTypes.h"
// #include "carb/assets/AssetsUtils.h"
// #include "carb/assets/IAssets.h"
// #include "carb/assets/IAssetsBlob.h"
// #include "carb/audio/AudioStreamerUtils.h"
// #include "carb/audio/AudioTypes.h"
// #include "carb/audio/AudioUtils.h"
// #include "carb/audio/IAudioCapture.h"
// #include "carb/audio/IAudioData.h"
// #include "carb/audio/IAudioDevice.h"
// #include "carb/audio/IAudioGroup.h"
// #include "carb/audio/IAudioPlayback.h"
// #include "carb/audio/IAudioUtils.h"
#include "carb/container/BufferedObject.h"
#include "carb/container/IntrusiveList.h"
#include "carb/container/IntrusiveUnorderedMultimap.h"
#include "carb/container/LocklessQueue.h"
#include "carb/container/LocklessStack.h"
#include "carb/container/RHUnorderedMap.h"
#include "carb/container/RHUnorderedMultimap.h"
#include "carb/container/RHUnorderedMultiset.h"
#include "carb/container/RHUnorderedSet.h"
#include "carb/container/RingBuffer.h"
#include "carb/container/RobinHoodImpl.h"
// #include "carb/crashreporter/CrashReporterUtils.h"
// #include "carb/crashreporter/ICrashReporter.h"
#include "carb/datasource/DataSourceTypes.h"
#include "carb/datasource/DataSourceUtils.h"
#include "carb/datasource/IDataSource.h"
#include "carb/delegate/Delegate.h"
#include "carb/detail/DeferredLoad.h"
#include "carb/detail/NoexceptType.h"
// #include "carb/dictionary/DictionaryUtils.h"
// #include "carb/dictionary/IDictionary.h"
// #include "carb/dictionary/ISerializer.h"
#include "carb/eventdispatcher/EventDispatcherTypes.h"
#include "carb/eventdispatcher/IEventDispatcher.h"
#include "carb/events/EventsUtils.h"
#include "carb/events/IEvents.h"
// #include "carb/extras/AppConfig.h"
// #include "carb/extras/ArenaAllocator.h"
// #include "carb/extras/Barrier.h"
// #include "carb/extras/Base64.h"
// #include "carb/extras/CmdLineParser.h"
// #include "carb/extras/CpuInfo.h"
// #include "carb/extras/Csv.h"
// #include "carb/extras/Debugging.h"
// #include "carb/extras/DomainSocket.h"
// #include "carb/extras/EnvironmentVariable.h"
// #include "carb/extras/EnvironmentVariableParser.h"
// #include "carb/extras/EnvironmentVariableUtils.h"
// #include "carb/extras/Errors.h"
// #include "carb/extras/FreeListAllocator.h"
// #include "carb/extras/Guid.h"
// #include "carb/extras/HandleDatabase.h"
// #include "carb/extras/Hash.h"
// #include "carb/extras/Latch.h"
// #include "carb/extras/Library.h"
// #include "carb/extras/MemoryUsage.h"
// #include "carb/extras/MultiFreeListAllocator.h"
// #include "carb/extras/Options.h"
// #include "carb/extras/Path.h"
// #include "carb/extras/ScopeExit.h"
// #include "carb/extras/Semaphore.h"
// #include "carb/extras/SharedMemory.h"
// #include "carb/extras/StringProcessor.h"
// #include "carb/extras/StringSafe.h"
// #include "carb/extras/StringUtils.h"
// #include "carb/extras/TestEnvironment.h"
// #include "carb/extras/Timer.h"
// #include "carb/extras/Tokens.h"
// #include "carb/extras/Unicode.h"
// #include "carb/extras/Utf8Parser.h"
// #include "carb/extras/Uuid.h"
// #include "carb/extras/VariableSetup.h"
// #include "carb/extras/WindowsPath.h"
#include "carb/filesystem/FindFiles.h"
#include "carb/filesystem/IFileSystem.h"
#include "carb/input/IInput.h"
#include "carb/input/InputProvider.h"
#include "carb/input/InputTypes.h"
#include "carb/input/InputUtils.h"
// #include "carb/l10n/IL10n.h"
// #include "carb/l10n/L10nUtils.h"
#include "carb/launcher/ILauncher.h"
#include "carb/launcher/LauncherUtils.h"
// #include "carb/logging/ILogging.h"
// #include "carb/logging/Log.h"
// #include "carb/logging/Logger.h"
// #include "carb/logging/LoggingSettingsUtils.h"
// #include "carb/logging/StandardLogger.h"
#include "carb/math/Util.h"
#include "carb/memory/ArenaAllocator.h"
#include "carb/memory/IMemoryTracker.h"
#include "carb/memory/Memory.h"
#include "carb/memory/MemoryTrackerDefines.h"
#include "carb/memory/MemoryTrackerReplaceAllocation.h"
#include "carb/memory/MemoryTrackerTypes.h"
#include "carb/memory/PooledAllocator.h"
#include "carb/memory/Util.h"
#include "carb/messaging/IMessaging.h"
#include "carb/messaging/MessagingTypes.h"
#include "carb/process/Util.h"
// #include "carb/profiler/IProfileMonitor.h"
// #include "carb/profiler/IProfiler.h"
// #include "carb/profiler/Profile.h"
// #include "carb/profiler/ProfilerUtils.h"
#include "carb/scripting/IScripting.h"
#include "carb/settings/ISettings.h"
#include "carb/settings/SettingsUtils.h"
// #include "carb/simplegui/ISimpleGui.h"
// #include "carb/simplegui/SimpleGuiTypes.h"
// #include "carb/tasking/IFiberEvents.h"
// #include "carb/tasking/ITasking.h"
// #include "carb/tasking/IThreadPool.h"
// #include "carb/tasking/TaskingHelpers.h"
// #include "carb/tasking/TaskingTypes.h"
// #include "carb/tasking/TaskingUtils.h"
// #include "carb/tasking/ThreadPoolUtils.h"
// #include "carb/thread/Futex.h"
// #include "carb/thread/FutexImpl.h"
// #include "carb/thread/IThreadUtil.h"
// #include "carb/thread/IpcLock.h"
// #include "carb/thread/Mutex.h"
// #include "carb/thread/RecursiveSharedMutex.h"
// #include "carb/thread/SharedMutex.h"
// #include "carb/thread/Spinlock.h"
// #include "carb/thread/ThreadLocal.h"
// #include "carb/thread/Util.h"
#include "carb/tokens/ITokens.h"
#include "carb/tokens/TokensUtils.h"
// #include "carb/typeinfo/ITypeInfo.h"
// #include "carb/typeinfo/TypeInfoRegistrationUtils.h"
// #include "carb/variant/IVariant.h"
// #include "carb/variant/VariantTypes.h"
// #include "carb/variant/VariantUtils.h"
// #include "carb/windowing/IGLContext.h"
// #include "carb/windowing/IWindowing.h"

// omni
// #include "omni/Function.h"
// #include "omni/Span.h"
// #include "omni/String.h"
// #include "omni/audio/AudioSettings.h"
// #include "omni/audio/IAudioDeviceEnum.h"
// #include "omni/audio/IAudioPlayer.h"
// #include "omni/audio/IAudioRecorder.h"
// #include "omni/audio/IUiAudio.h"
// #include "omni/compiletime/CompileTime.h"
#include "omni/core/Api.h"
#include "omni/core/Assert.h"
#include "omni/core/BuiltIn.h"
#include "omni/core/IObject.h"
#include "omni/core/ITypeFactory.h"
#include "omni/core/Interface.h"
#include "omni/core/ModuleExports.h"
#include "omni/core/ModuleInfo.h"
#include "omni/core/Omni.h"
#include "omni/core/OmniAttr.h"
#include "omni/core/OmniInit.h"
#include "omni/core/Platform.h"
#include "omni/core/ReplaceCarbAssert.h"
#include "omni/core/Result.h"
#include "omni/core/ResultError.h"
#include "omni/core/TypeId.h"
#include "omni/core/Types.h"
#include "omni/core/VariadicMacroUtils.h"
// #include "omni/detail/FunctionImpl.h"
// #include "omni/detail/PointerIterator.h"
#include "omni/ext/ExtensionsUtils.h"
#include "omni/ext/IExt.h"
#include "omni/ext/IExtensionData.h"
#include "omni/ext/IExtensionHooks.h"
#include "omni/ext/IExtensions.h"
// #include "omni/extras/ContainerHelper.h"
// #include "omni/extras/DataStreamer.h"
// #include "omni/extras/DictHelpers.h"
// #include "omni/extras/FileSystemHelpers.h"
// #include "omni/extras/ForceLink.h"
// #include "omni/extras/OutArrayUtils.h"
// #include "omni/extras/PathMap.h"
// #include "omni/extras/PrivacySettings.h"
// #include "omni/extras/RtxSettings.h"
// #include "omni/extras/ScratchBuffer.h"
// #include "omni/extras/SettingsHelpers.h"
// #include "omni/extras/StringHelpers.h"
// #include "omni/extras/UniqueApp.h"
// #include "omni/extras/Version.h"
// #include "omni/extras/md5.h"
#include "omni/geometry/Geometry.h"
// #include "omni/graph/core/Accessors.h"
// #include "omni/graph/core/ArrayWrapper.h"
// #include "omni/graph/core/BundleAttrib.h"
// #include "omni/graph/core/BundleAttribImpl.h"
// #include "omni/graph/core/BundlePrims.h"
// #include "omni/graph/core/BundlePrimsImpl.h"
#include "omni/graph/core/ComputeGraph.h"
// #include "omni/graph/core/ConstBundlePrims.h"
// #include "omni/graph/core/ConstBundlePrimsImpl.h"
// #include "omni/graph/core/GpuArray.h"
// #include "omni/graph/core/GpuInteropEntryUserData.h"
// #include "omni/graph/core/Handle.h"
// #include "omni/graph/core/IAttributeType.h"
// #include "omni/graph/core/IBundle.h"
// #include "omni/graph/core/IBundleFactory.h"
// #include "omni/graph/core/IConstBundle.h"
// #include "omni/graph/core/IDataModel.h"
// #include "omni/graph/core/IDirtyID.h"
// #include "omni/graph/core/IGraphRegistry.h"
// #include "omni/graph/core/IInternal.h"
// #include "omni/graph/core/INodeCategories.h"
// #include "omni/graph/core/ISchedulingHints.h"
// #include "omni/graph/core/IVariable.h"
// #include "omni/graph/core/IVariable2.h"
// #include "omni/graph/core/NodeTypeRegistrar.h"
// #include "omni/graph/core/NodeTypeRegistryTemplates.h"
// #include "omni/graph/core/StringUtils.h"
// #include "omni/graph/core/TemplateUtils.h"
// #include "omni/graph/core/Type.h"
// #include "omni/graph/core/bundle/IBundleFactory1.h"
// #include "omni/graph/core/bundle/IBundleFactory2.h"
// #include "omni/graph/core/iAttributeData.h"
// #include "omni/graph/core/iComputeGraph.h"
// #include "omni/graph/core/tuple.h"
// #include "omni/graph/ui/IOmniGraphUi.h"
// #include "omni/hydra/IDebug.h"
// #include "omni/hydra/IOmniHydra.h"
// #include "omni/hydra/ISceneDelegate.h"
// #include "omni/hydra/OmniHydraTypes.h"
// #include "omni/inspect/IInspectJsonSerializer.h"
// #include "omni/inspect/IInspectMemoryUse.h"
// #include "omni/inspect/IInspectSerializer.h"
// #include "omni/inspect/IInspector.h"
// #include "omni/inspect/MemorySizes.h"
#include "omni/kit/AssetUtils.h"
#include "omni/kit/ContentUiTypes.h"
#include "omni/kit/ContentWindowUtils.h"
// #include "omni/kit/EditorUsd.h"
#include "omni/kit/EventSubscribers.h"
#include "omni/kit/ExtensionWindowTypes.h"
#include "omni/kit/FilterGroup.h"
#include "omni/kit/IApp.h"
#include "omni/kit/IAppMessageBox.h"
#include "omni/kit/IAppWindow.h"
#include "omni/kit/IConsole.h"
#include "omni/kit/IContentUi.h"
#include "omni/kit/IExtensionWindow.h"
#include "omni/kit/IFileDialog.h"
#include "omni/kit/IMinimal.h"
#include "omni/kit/IRunLoopRunner.h"
#include "omni/kit/IScriptEditor.h"
#include "omni/kit/ISearch.h"
#include "omni/kit/IStageUpdate.h"
#include "omni/kit/ITagging.h"
#include "omni/kit/IViewport.h"
#include "omni/kit/KitTypes.h"
#include "omni/kit/KitUpdateOrder.h"
// #include "omni/kit/KitUtils.h"
#include "omni/kit/SettingsUtils.h"
#include "omni/kit/ValueGuard.h"
#include "omni/kit/ViewportTypes.h"
#include "omni/kit/ViewportWindowUtils.h"
#include "omni/kit/Wildcard.h"
#include "omni/kit/actions/core/Action.h"
#include "omni/kit/actions/core/IAction.h"
#include "omni/kit/actions/core/IActionRegistry.h"
#include "omni/kit/actions/core/LambdaAction.h"
#include "omni/kit/commands/Command.h"
#include "omni/kit/commands/ICommand.h"
#include "omni/kit/commands/ICommandBridge.h"
// #include "omni/kit/renderer/IGpuFoundation.h"
// #include "omni/kit/renderer/IImGuiRenderer.h"
// #include "omni/kit/renderer/IRenderer.h"
// #include "omni/kit/renderer/RendererUtils.h"
// #include "omni/kit/ui/Api.h"
// #include "omni/kit/ui/AssetDragDropHandler.h"
// #include "omni/kit/ui/BroadcastModel.h"
// #include "omni/kit/ui/Button.h"
// #include "omni/kit/ui/CheckBox.h"
// #include "omni/kit/ui/CollapsingFrame.h"
// #include "omni/kit/ui/Color.h"
// #include "omni/kit/ui/ColorScheme.h"
// #include "omni/kit/ui/ColumnLayout.h"
// #include "omni/kit/ui/ComboBox.h"
// #include "omni/kit/ui/Common.h"
// #include "omni/kit/ui/Container.h"
// #include "omni/kit/ui/ContentWindow.h"
// #include "omni/kit/ui/Drag.h"
// #include "omni/kit/ui/Field.h"
// #include "omni/kit/ui/FilePicker.h"
// #include "omni/kit/ui/FilterGroupWidget.h"
// #include "omni/kit/ui/HotkeyUtils.h"
// #include "omni/kit/ui/Image.h"
// #include "omni/kit/ui/Label.h"
// #include "omni/kit/ui/Library.h"
// #include "omni/kit/ui/ListBox.h"
// #include "omni/kit/ui/Menu.h"
// #include "omni/kit/ui/Model.h"
// #include "omni/kit/ui/ModelMeta.h"
// #include "omni/kit/ui/ModelWidget.h"
// #include "omni/kit/ui/NativeFileDialog.h"
// #include "omni/kit/ui/Popup.h"
// #include "omni/kit/ui/PopupDialog.h"
// #include "omni/kit/ui/ProgressBar.h"
// #include "omni/kit/ui/RowColumnLayout.h"
// #include "omni/kit/ui/RowLayout.h"
// #include "omni/kit/ui/ScalarXYZ.h"
// #include "omni/kit/ui/ScalarXYZW.h"
// #include "omni/kit/ui/ScrollingFrame.h"
// #include "omni/kit/ui/Separator.h"
// #include "omni/kit/ui/SimpleTreeView.h"
// #include "omni/kit/ui/Slider.h"
// #include "omni/kit/ui/Spacer.h"
// #include "omni/kit/ui/TextBox.h"
// #include "omni/kit/ui/Transform.h"
// #include "omni/kit/ui/UI.h"
// #include "omni/kit/ui/ValueWidget.h"
// #include "omni/kit/ui/ViewCollapsing.h"
// #include "omni/kit/ui/Widget.h"
// #include "omni/kit/ui/Window.h"
// #include "omni/kit/ui/WindowStandalone.h"
#include "omni/kit/usd/layers/ILayers.h"
#include "omni/kit/usd/layers/ILayersState.h"
#include "omni/kit/usd/layers/IWorkflowAutoAuthoring.h"
#include "omni/kit/usd/layers/IWorkflowLiveSyncing.h"
#include "omni/kit/usd/layers/IWorkflowSpecsLinking.h"
#include "omni/kit/usd/layers/IWorkflowSpecsLocking.h"
#include "omni/kit/usd/layers/LayerTypes.h"
#include "omni/kit/xr/XRBootstrap.h"
// #include "omni/log/ILog.h"
// #include "omni/log/ILogChannelFilter.h"
// #include "omni/log/LogChannel.h"
// #include "omni/log/LogChannelFilterUtils.h"
// #include "omni/log/WildcardLogChannelFilter.h"
// #include "omni/math/linalg/SafeCast.h"
// #include "omni/math/linalg/debug.h"
// #include "omni/math/linalg/half.h"
// #include "omni/math/linalg/math.h"
// #include "omni/math/linalg/matrix.h"
// #include "omni/math/linalg/quat.h"
// #include "omni/math/linalg/vec.h"
// #include "omni/platforminfo/ICpuInfo.h"
// #include "omni/platforminfo/IDisplayInfo.h"
// #include "omni/platforminfo/IMemoryInfo.h"
// #include "omni/platforminfo/IOsInfo.h"
// #include "omni/platforminfo/IOsInfo2.h"
// #include "omni/renderer/IDebugDraw.h"
#include "omni/renderer/utils/AssetsManagement.h"
// #include "omni/resourcemonitor/IResourceMonitor.h"
// #include "omni/resourcemonitor/ResourceMonitorSettings.h"
// #include "omni/resourcemonitor/ResourceMonitorTypes.h"
// #include "omni/str/IReadOnlyCString.h"
// #include "omni/str/Wildcard.h"
// #include "omni/structuredlog/BinarySerializer.h"
// #include "omni/structuredlog/IStructuredLog.h"
// #include "omni/structuredlog/IStructuredLogControl.h"
// #include "omni/structuredlog/IStructuredLogFromILog.h"
// #include "omni/structuredlog/IStructuredLogSettings.h"
// #include "omni/structuredlog/IStructuredLogSettings2.h"
// #include "omni/structuredlog/JsonSerializer.h"
// #include "omni/structuredlog/JsonTree.h"
// #include "omni/structuredlog/JsonTreeSerializer.h"
// #include "omni/structuredlog/StringView.h"
// #include "omni/structuredlog/StructuredLogCommon.h"
// #include "omni/structuredlog/StructuredLogSettingsUtils.h"
// #include "omni/structuredlog/StructuredLogStandalone.h"
// #include "omni/structuredlog/StructuredLogUtils.h"
// #include "omni/structuredlog/Telemetry.h"
// #include "omni/telemetry/ITelemetry.h"
// #include "omni/telemetry/ITelemetry2.h"
#include "omni/timeline/ITimeline.h"
#include "omni/timeline/TimelineTypes.h"
// #include "omni/ui/AbstractField.h"
// #include "omni/ui/AbstractItemDelegate.h"
// #include "omni/ui/AbstractItemModel.h"
// #include "omni/ui/AbstractMultiField.h"
// #include "omni/ui/AbstractSlider.h"
// #include "omni/ui/AbstractValueModel.h"
// #include "omni/ui/Alignment.h"
// #include "omni/ui/Api.h"
// #include "omni/ui/ArrowHelper.h"
// #include "omni/ui/Axis.h"
// #include "omni/ui/BezierCurve.h"
// #include "omni/ui/Button.h"
// #include "omni/ui/Callback.h"
// #include "omni/ui/CanvasFrame.h"
// #include "omni/ui/CheckBox.h"
// #include "omni/ui/Circle.h"
// #include "omni/ui/CollapsableFrame.h"
// #include "omni/ui/ColorWidget.h"
// #include "omni/ui/ComboBox.h"
// #include "omni/ui/Container.h"
// #include "omni/ui/ContainerScope.h"
// #include "omni/ui/CornerFlag.h"
// #include "omni/ui/DockSpace.h"
// #include "omni/ui/Ellipse.h"
// #include "omni/ui/FloatDrag.h"
// #include "omni/ui/FloatField.h"
// #include "omni/ui/FloatSlider.h"
// #include "omni/ui/Font.h"
// #include "omni/ui/FontAtlasTexture.h"
// #include "omni/ui/FontHelper.h"
// #include "omni/ui/Frame.h"
// #include "omni/ui/FreeShape.h"
// #include "omni/ui/Grid.h"
// #include "omni/ui/HGrid.h"
// #include "omni/ui/HStack.h"
// #include "omni/ui/IGlyphManager.h"
// #include "omni/ui/Image.h"
// #include "omni/ui/ImageProvider/AssetsState.h"
// #include "omni/ui/ImageProvider/ByteImageProvider.h"
// #include "omni/ui/ImageProvider/DynamicTextureProvider.h"
// #include "omni/ui/ImageProvider/ImageProvider.h"
// #include "omni/ui/ImageProvider/RasterImageProvider.h"
// #include "omni/ui/ImageProvider/VectorImageProvider.h"
// #include "omni/ui/ImageWithProvider.h"
// #include "omni/ui/Inspector.h"
// #include "omni/ui/IntDrag.h"
// #include "omni/ui/IntField.h"
// #include "omni/ui/IntSlider.h"
// #include "omni/ui/InvisibleButton.h"
// #include "omni/ui/ItemModelHelper.h"
// #include "omni/ui/Label.h"
// #include "omni/ui/Length.h"
// #include "omni/ui/Line.h"
// #include "omni/ui/MainWindow.h"
// #include "omni/ui/Menu.h"
// #include "omni/ui/MenuBar.h"
// #include "omni/ui/MenuDelegate.h"
// #include "omni/ui/MenuHelper.h"
// #include "omni/ui/MenuItem.h"
// #include "omni/ui/MenuItemCollection.h"
// #include "omni/ui/MultiDragField.h"
// #include "omni/ui/MultiField.h"
// #include "omni/ui/Object.h"
// #include "omni/ui/OffsetLine.h"
// #include "omni/ui/Placer.h"
// #include "omni/ui/Plot.h"
// #include "omni/ui/Profile.h"
// #include "omni/ui/ProgressBar.h"
// #include "omni/ui/Property.h"
// #include "omni/ui/RadioButton.h"
// #include "omni/ui/RadioCollection.h"
// #include "omni/ui/RasterHelper.h"
// #include "omni/ui/RasterPolicy.h"
// #include "omni/ui/Rectangle.h"
// #include "omni/ui/ScrollBarPolicy.h"
// #include "omni/ui/ScrollingFrame.h"
// #include "omni/ui/Separator.h"
// #include "omni/ui/ShadowFlag.h"
// #include "omni/ui/Shape.h"
// #include "omni/ui/SimpleListModel.h"
// #include "omni/ui/SimpleNumericModel.h"
// #include "omni/ui/SimpleStringModel.h"
// #include "omni/ui/Spacer.h"
// #include "omni/ui/Stack.h"
// #include "omni/ui/StringField.h"
// #include "omni/ui/Style.h"
// #include "omni/ui/StyleContainer.h"
// #include "omni/ui/StyleProperties.h"
// #include "omni/ui/StyleStore.h"
// #include "omni/ui/ToolBar.h"
// #include "omni/ui/ToolButton.h"
// #include "omni/ui/TreeView.h"
// #include "omni/ui/Triangle.h"
// #include "omni/ui/VGrid.h"
// #include "omni/ui/VStack.h"
// #include "omni/ui/ValueModelHelper.h"
// #include "omni/ui/Widget.h"
// #include "omni/ui/Window.h"
// #include "omni/ui/WindowHandle.h"
// #include "omni/ui/Workspace.h"
// #include "omni/ui/ZStack.h"
// #include "omni/ui/scene/AbstractContainer.h"
// #include "omni/ui/scene/AbstractDrawSystem.h"
// #include "omni/ui/scene/AbstractGesture.h"
// #include "omni/ui/scene/AbstractItem.h"
// #include "omni/ui/scene/AbstractManipulatorModel.h"
// #include "omni/ui/scene/AbstractShape.h"
// #include "omni/ui/scene/Api.h"
// #include "omni/ui/scene/Arc.h"
// #include "omni/ui/scene/Callback.h"
// #include "omni/ui/scene/CameraModel.h"
// #include "omni/ui/scene/ClickGesture.h"
// #include "omni/ui/scene/Culling.h"
// #include "omni/ui/scene/Curve.h"
// #include "omni/ui/scene/DoubleClickGesture.h"
// #include "omni/ui/scene/DragGesture.h"
// #include "omni/ui/scene/DrawBuffer.h"
// #include "omni/ui/scene/DrawBufferIndex.h"
// #include "omni/ui/scene/DrawList.h"
// #include "omni/ui/scene/GestureManager.h"
// #include "omni/ui/scene/HoverGesture.h"
// #include "omni/ui/scene/Image.h"
// #include "omni/ui/scene/ImageHelper.h"
// #include "omni/ui/scene/ImguiDrawSystem.h"
// #include "omni/ui/scene/Label.h"
// #include "omni/ui/scene/Line.h"
// #include "omni/ui/scene/Manipulator.h"
// #include "omni/ui/scene/ManipulatorGesture.h"
// #include "omni/ui/scene/ManipulatorModelHelper.h"
// #include "omni/ui/scene/Math.h"
// #include "omni/ui/scene/Object.h"
// #include "omni/ui/scene/Points.h"
// #include "omni/ui/scene/PolygonMesh.h"
// #include "omni/ui/scene/Rectangle.h"
// #include "omni/ui/scene/Scene.h"
// #include "omni/ui/scene/SceneContainerScope.h"
// #include "omni/ui/scene/SceneView.h"
// #include "omni/ui/scene/Screen.h"
// #include "omni/ui/scene/ScrollGesture.h"
// #include "omni/ui/scene/ShapeGesture.h"
// #include "omni/ui/scene/Space.h"
// #include "omni/ui/scene/TexturedMesh.h"
// #include "omni/ui/scene/Transform.h"
// #include "omni/ui/scene/TransformBasis.h"
// #include "omni/ui/scene/Widget.h"
// #include "omni/ui/windowmanager/IWindowCallbackManager.h"
// #include "omni/ui/windowmanager/WindowManagerUtils.h"
#include "omni/usd/UsdContextIncludes.h"
#include "omni/usd/UtilsIncludes.h"
// #include "omni/usd/Api.h"
// #include "omni/usd/AssetUtils.h"
// #include "omni/usd/IStageAudio.h"
// #include "omni/usd/LayerUtils.h"
// #include "omni/usd/PathUtils.h"
// #include "omni/usd/Selection.h"
#include "omni/usd/UsdContext.h"
// #include "omni/usd/UsdContextOverrides.h"
#include "omni/usd/UsdManager.h"
// #include "omni/usd/UsdTypes.h"
// #include "omni/usd/UsdUtils.h"
// #include "omni/usd/ViewportTypes.h"
// #include "omni/usdrthydra/ISceneDelegate.h"
// #include "omni/videoencoding/IVideoEncoding.h"

// omni::physics
#include "omni/physx/placeholder.h"

// omni::fabric
#include "omni/fabric/AttrNameAndType.h"
#include "omni/fabric/Enums.h"
#include "omni/fabric/FabricTypes.h"
// #include "omni/fabric/FabricUSD.h"
#include "omni/fabric/IFabric.h"
#include "omni/fabric/IFabricInspector.h"
#include "omni/fabric/IPath.h"
#include "omni/fabric/IToken.h"
#include "omni/fabric/IdTypes.h"
#include "omni/fabric/Ordered_Set.h"
#include "omni/fabric/PrimChanges.h"
#include "omni/fabric/RationalTime.h"
// #include "omni/fabric/SimStageWithHistory.h"
#include "omni/fabric/Type.h"
// #include "omni/fabric/USDValueAccessors.h"
// #include "omni/fabric/WrapperImpl.h"
// #include "omni/fabric/batch/BatchFilter.h"
// #include "omni/fabric/batch/BitArray.h"
// #include "omni/fabric/batch/Defines.h"
// #include "omni/fabric/batch/IBatch.h"
// #include "omni/fabric/batch/Lambda.h"
#include "omni/fabric/batch/Types.h"
#include "omni/fabric/batch/View.h"
// #include "omni/gpucompute/D3dContext.h"
#include "omni/gpucompute/GpuCompute.h"

// usdrt::scenegraph::usd::physxSchema
#include "usdrt/scenegraph/usd/physxSchema/jointStateAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxArticulationAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxArticulationForceSensorAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxAutoAttachmentAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxAutoParticleClothAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxCameraAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxCameraDroneAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxCameraFollowAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxCameraFollowLookAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxCameraFollowVelocityAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxCharacterControllerAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxCollisionAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxContactReportAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxConvexDecompositionCollisionAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxConvexHullCollisionAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxCookedDataAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxDeformableAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxDeformableBodyAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxDeformableBodyMaterialAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxDeformableSurfaceAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxDeformableSurfaceMaterialAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxDiffuseParticlesAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxForceAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxHairAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxHairMaterialAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxJointAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxLimitAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxMaterialAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxParticleAnisotropyAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxParticleAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxParticleClothAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxParticleIsosurfaceAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxParticleSamplingAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxParticleSetAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxParticleSmoothingAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxParticleSystem.h"
#include "usdrt/scenegraph/usd/physxSchema/physxPBDMaterialAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxPhysicsAttachment.h"
#include "usdrt/scenegraph/usd/physxSchema/physxPhysicsDistanceJointAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxPhysicsGearJoint.h"
#include "usdrt/scenegraph/usd/physxSchema/physxPhysicsInstancer.h"
#include "usdrt/scenegraph/usd/physxSchema/physxPhysicsJointInstancer.h"
#include "usdrt/scenegraph/usd/physxSchema/physxPhysicsRackAndPinionJoint.h"
#include "usdrt/scenegraph/usd/physxSchema/physxRigidBodyAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxSceneAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxSDFMeshCollisionAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxSphereFillCollisionAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxTendonAttachmentAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxTendonAttachmentLeafAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxTendonAttachmentRootAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxTendonAxisAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxTendonAxisRootAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxTriangleMeshCollisionAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxTriangleMeshSimplificationCollisionAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxTriggerAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxTriggerStateAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleAckermannSteeringAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleAutoGearBoxAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleBrakesAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleClutchAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleContextAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleControllerAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleDriveBasicAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleDriveStandardAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleEngineAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleGearsAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleMultiWheelDifferentialAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleSteeringAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleSuspensionAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleSuspensionComplianceAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleTankControllerAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleTankDifferentialAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleTireAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleTireFrictionTable.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleWheelAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleWheelAttachmentAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/physxVehicleWheelControllerAPI.h"
#include "usdrt/scenegraph/usd/physxSchema/tetrahedralMesh.h"
#include "usdrt/scenegraph/usd/physxSchema/tokens.h"