//! Raw FFI bindings from `bindgen` and `autocxx`.
#![allow(clippy::all)]
#![allow(unused_imports)]
use autocxx::prelude::*;
pub use ffi_autocxx::*;

cpp::cpp! {{
    #include "omniverse_sys/omni.h"

    // Declare this compilation unit as carbonite language bindings
    // Underneath, CARB_GLOBALS macro is also expanded (required)
    CARB_BINDINGS("rust");
}}

#[allow(dead_code)]
pub(crate) mod ffi_bindgen {
    // Include rust code generated by bindgen
    include!(concat!(env!("OUT_DIR"), "/bindgen.rs"));

    // Re-export types from bindgen directly under ffi_bindgen module
    pub use root::*;

    // Declare external types for `ffi_autocxx` module (autocxx cannot generate these as of now)
    crate::macros::impl_extern_type! {
        [Trivial]
        carb::PluginLoadingDesc = "carb::PluginLoadingDesc"
        omni::kit::AppDesc = "omni::kit::AppDesc"
        omni::kit::PlatformInfo = "omni::kit::PlatformInfo"
        omni::kit::RunLoop = "omni::kit::RunLoop"
    }
}

include_cpp! {
    #include "omniverse_sys/omni.h"

    // Generate unsafe bindings in `ffi_autocxx` module
    name!(ffi_autocxx)
    safety!(unsafe)

    // Exclude utilities
    exclude_utilities!()

    // Declare external types from `ffi_bindgen` module (autocxx cannot generate these as of now)
    extern_cpp_type!("carb::PluginLoadingDesc", crate::ffi::bindings::ffi_bindgen::carb::PluginLoadingDesc)
    extern_cpp_type!("omni::kit::AppDesc", crate::ffi::bindings::ffi_bindgen::omni::kit::AppDesc)
    extern_cpp_type!("omni::kit::PlatformInfo", crate::ffi::bindings::ffi_bindgen::omni::kit::PlatformInfo)
    extern_cpp_type!("omni::kit::RunLoop", crate::ffi::bindings::ffi_bindgen::omni::kit::RunLoop)

    // Generate cxx bindings
    generate!("carb::Framework")
    generate!("carb::getFramework")
    generate!("carb::settings::ISettings")

    generate!("omni::kit::getDefaultViewportWindow")
    generate!("omni::kit::IApp")
    generate!("omni::kit::IStageUpdate")
    generate!("omni::kit::IAppScripting")
    generate!("omni::kit::IViewport")
    generate!("omni::kit::IViewportWindow")

    generate!("omni::physx::IPhysx")
    generate!("omni::physx::IPhysxSimulation")

    generate!("omni::timeline::Timeline")
    generate!("omni::timeline::TimelinePtr")

    generate_pod!("omni::usd::UsdManager")
    generate!("omni::usd::UsdContext")

    // Declare external types coming from other sys crates
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfBBox3d", pxr::pxr::GfBBox3d)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfCamera", pxr::pxr::GfCamera)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfDualQuatd", pxr::pxr::GfDualQuatd)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfDualQuatf", pxr::pxr::GfDualQuatf)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfDualQuath", pxr::pxr::GfDualQuath)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfFrustum", pxr::pxr::GfFrustum)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfInterval", pxr::pxr::GfInterval)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfLine", pxr::pxr::GfLine)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfLine2d", pxr::pxr::GfLine2d)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfLineSeg", pxr::pxr::GfLineSeg)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfLineSeg2d", pxr::pxr::GfLineSeg2d)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfMatrix2d", pxr::pxr::GfMatrix2d)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfMatrix2f", pxr::pxr::GfMatrix2f)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfMatrix3d", pxr::pxr::GfMatrix3d)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfMatrix3f", pxr::pxr::GfMatrix3f)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfMatrix4d", pxr::pxr::GfMatrix4d)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfMatrix4f", pxr::pxr::GfMatrix4f)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfPlane", pxr::pxr::GfPlane)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfQuatd", pxr::pxr::GfQuatd)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfQuaternion", pxr::pxr::GfQuaternion)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfQuatf", pxr::pxr::GfQuatf)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfQuath", pxr::pxr::GfQuath)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfRange1d", pxr::pxr::GfRange1d)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfRange1f", pxr::pxr::GfRange1f)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfRange2d", pxr::pxr::GfRange2d)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfRange2f", pxr::pxr::GfRange2f)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfRange3d", pxr::pxr::GfRange3d)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfRange3f", pxr::pxr::GfRange3f)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfRay", pxr::pxr::GfRay)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfRect2i", pxr::pxr::GfRect2i)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfRotation", pxr::pxr::GfRotation)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfSize2", pxr::pxr::GfSize2)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfSize3", pxr::pxr::GfSize3)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfTransform", pxr::pxr::GfTransform)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfVec2d", pxr::pxr::GfVec2d)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfVec2f", pxr::pxr::GfVec2f)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfVec2h", pxr::pxr::GfVec2h)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfVec2i", pxr::pxr::GfVec2i)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfVec3d", pxr::pxr::GfVec3d)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfVec3f", pxr::pxr::GfVec3f)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfVec3h", pxr::pxr::GfVec3h)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfVec3i", pxr::pxr::GfVec3i)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfVec4d", pxr::pxr::GfVec4d)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfVec4f", pxr::pxr::GfVec4f)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfVec4h", pxr::pxr::GfVec4h)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::GfVec4i", pxr::pxr::GfVec4i)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfAttributeSpec", pxr::pxr::SdfAttributeSpec)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfCleanupEnabler", pxr::pxr::SdfCleanupEnabler)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfFileFormat", pxr::pxr::SdfFileFormat)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfLayer", pxr::pxr::SdfLayer)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfLayerHandle", pxr::pxr::SdfLayerHandle)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfLayerOffset", pxr::pxr::SdfLayerOffset)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfLayerRefPtr", pxr::pxr::SdfLayerRefPtr)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfPath", pxr::pxr::SdfPath)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfPropertySpec", pxr::pxr::SdfPropertySpec)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfReference", pxr::pxr::SdfReference)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfRelationshipSpec", pxr::pxr::SdfRelationshipSpec)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfSite", pxr::pxr::SdfSite)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfSpec", pxr::pxr::SdfSpec)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfTimeCode", pxr::pxr::SdfTimeCode)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfValueTypeName", pxr::pxr::SdfValueTypeName)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfVariantSpec", pxr::pxr::SdfVariantSpec)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::TfEnum", pxr::pxr::TfEnum)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::TfSingleton", pxr::pxr::TfSingleton)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::TfToken", pxr::pxr::TfToken)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::TfType", pxr::pxr::TfType)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::TfTypeInfoMap", pxr::pxr::TfTypeInfoMap)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::Usd_PrimFlagsPredicate", pxr::pxr::Usd_PrimFlagsPredicate)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdAPISchemaBase", pxr::pxr::UsdAPISchemaBase)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdAttribute", pxr::pxr::UsdAttribute)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdCollectionAPI", pxr::pxr::UsdCollectionAPI)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomBasisCurves", pxr::pxr::UsdGeomBasisCurves)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomBBoxCache", pxr::pxr::UsdGeomBBoxCache)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomCamera", pxr::pxr::UsdGeomCamera)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomCapsule", pxr::pxr::UsdGeomCapsule)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomCone", pxr::pxr::UsdGeomCone)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomConstraintTarget", pxr::pxr::UsdGeomConstraintTarget)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomCube", pxr::pxr::UsdGeomCube)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomCylinder", pxr::pxr::UsdGeomCylinder)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomGprim", pxr::pxr::UsdGeomGprim)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomImageable", pxr::pxr::UsdGeomImageable)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomMesh", pxr::pxr::UsdGeomMesh)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomNurbsCurves", pxr::pxr::UsdGeomNurbsCurves)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomNurbsPatch", pxr::pxr::UsdGeomNurbsPatch)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomPointInstancer", pxr::pxr::UsdGeomPointInstancer)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomPoints", pxr::pxr::UsdGeomPoints)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomPrimvar", pxr::pxr::UsdGeomPrimvar)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomSphere", pxr::pxr::UsdGeomSphere)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomTokensType", pxr::pxr::UsdGeomTokensType)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomXform", pxr::pxr::UsdGeomXform)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomXformable", pxr::pxr::UsdGeomXformable)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomXformCache", pxr::pxr::UsdGeomXformCache)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdGeomXformOp", pxr::pxr::UsdGeomXformOp)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdHydraTokensType", pxr::pxr::UsdHydraTokensType)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdInherits", pxr::pxr::UsdInherits)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdNotice", pxr::pxr::UsdNotice)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdObject", pxr::pxr::UsdObject)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPayloads", pxr::pxr::UsdPayloads)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsArticulationRootAPI", pxr::pxr::UsdPhysicsArticulationRootAPI)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsCollisionAPI", pxr::pxr::UsdPhysicsCollisionAPI)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsCollisionGroup", pxr::pxr::UsdPhysicsCollisionGroup)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsDistanceJoint", pxr::pxr::UsdPhysicsDistanceJoint)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsDriveAPI", pxr::pxr::UsdPhysicsDriveAPI)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsFilteredPairsAPI", pxr::pxr::UsdPhysicsFilteredPairsAPI)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsFixedJoint", pxr::pxr::UsdPhysicsFixedJoint)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsJoint", pxr::pxr::UsdPhysicsJoint)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsLimitAPI", pxr::pxr::UsdPhysicsLimitAPI)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsMassAPI", pxr::pxr::UsdPhysicsMassAPI)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsMassUnits", pxr::pxr::UsdPhysicsMassUnits)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsMaterialAPI", pxr::pxr::UsdPhysicsMaterialAPI)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsMeshCollisionAPI", pxr::pxr::UsdPhysicsMeshCollisionAPI)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsPrismaticJoint", pxr::pxr::UsdPhysicsPrismaticJoint)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsRevoluteJoint", pxr::pxr::UsdPhysicsRevoluteJoint)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsRigidBodyAPI", pxr::pxr::UsdPhysicsRigidBodyAPI)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsScene", pxr::pxr::UsdPhysicsScene)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsSphericalJoint", pxr::pxr::UsdPhysicsSphericalJoint)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsTokens", pxr::pxr::UsdPhysicsTokens)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsTokensType", pxr::pxr::UsdPhysicsTokensType)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsTokensType", pxr::pxr::UsdPhysicsTokensType)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPrim", pxr::pxr::UsdPrim)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPrimCompositionQuery", pxr::pxr::UsdPrimCompositionQuery)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPrimCompositionQueryArc", pxr::pxr::UsdPrimCompositionQueryArc)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPrimDefinition", pxr::pxr::UsdPrimDefinition)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPrimRange_iterator", pxr::pxr::UsdPrimRange_iterator)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPrimRange", pxr::pxr::UsdPrimRange)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPrimSiblingRange", pxr::pxr::UsdPrimSiblingRange)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPrimSubtreeRange", pxr::pxr::UsdPrimSubtreeRange)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdPrimTypeInfo", pxr::pxr::UsdPrimTypeInfo)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdProcTokensType", pxr::pxr::UsdProcTokensType)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdProperty", pxr::pxr::UsdProperty)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdReferences", pxr::pxr::UsdReferences)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdRelationship", pxr::pxr::UsdRelationship)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdRenderTokensType", pxr::pxr::UsdRenderTokensType)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdResolveInfo", pxr::pxr::UsdResolveInfo)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdResolveTarget", pxr::pxr::UsdResolveTarget)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdSchemaBase", pxr::pxr::UsdSchemaBase)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdStage", pxr::pxr::UsdStage)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdStageCache", pxr::pxr::UsdStageCache)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdStageCacheContext", pxr::pxr::UsdStageCacheContext)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdStageRefPtr", pxr::pxr::UsdStageRefPtr)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdStageWeakPtr", pxr::pxr::UsdStageWeakPtr)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdTimeCode", pxr::pxr::UsdTimeCode)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdTyped", pxr::pxr::UsdTyped)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdUtilsRegisteredVariantSet", pxr::pxr::UsdUtilsRegisteredVariantSet)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdUtilsSparseAttrValueWriter", pxr::pxr::UsdUtilsSparseAttrValueWriter)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdUtilsSparseValueWriter", pxr::pxr::UsdUtilsSparseValueWriter)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdUtilsStageCache", pxr::pxr::UsdUtilsStageCache)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdUtilsTimeCodeRange", pxr::pxr::UsdUtilsTimeCodeRange)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdVariantSet", pxr::pxr::UsdVariantSet)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdVariantSets", pxr::pxr::UsdVariantSets)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdZipFile", pxr::pxr::UsdZipFile)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::VtDictionary", pxr::pxr::VtDictionary)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::VtValue", pxr::pxr::VtValue)
}

// pub use ffi_autocxx_usdrt::omni::fabric as usdrt_fabric;
// pub use ffi_autocxx_usdrt::usdrt;
// include_cpp! {
//     #include "omniverse_sys/omni.h"

//     // Generate unsafe bindings in `ffi_autocxx_usdrt` module
//     name!(ffi_autocxx_usdrt)
//     safety!(unsafe)

//     // Exclude utilities
//     exclude_utilities!()

//     // Generate cxx bindings
//     generate!("omni::fabric::StageReaderWriterId")
//     generate!("omni::fabric::UsdStageId")

//     generate!("usdrt::PhysxSchemaPhysxCollisionAPI")
//     generate!("usdrt::PhysxSchemaPhysxSDFMeshCollisionAPI")
//     generate!("usdrt::PhysxSchemaPhysxTriangleMeshCollisionAPI")

//     generate!("usdrt::SdfPath")

//     generate!("usdrt::UsdAPISchemaBase")
//     generate!("usdrt::UsdAttribute")
//     generate!("usdrt::UsdPrim")
//     generate!("usdrt::UsdRelationship")
//     generate!("usdrt::UsdSchemaBase")
//     generate!("usdrt::UsdStage")
// }
